# Generated by Django 4.2 on 2023-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('current_weight', models.FloatField()),
                ('goal', models.CharField(choices=[('weight loss', 'Weight Loss'), ('weight gain', 'Weight Gain'), ('maintain weight', 'Maintain Weight')], max_length=15)),
                ('goal_weight', models.FloatField()),
                ('activity', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('weekly_weight_change', models.FloatField()),
            ],
        ),
    ]
