# Generated by Django 4.2 on 2023-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_weight_change',
            field=models.FloatField(default=0.0),
        ),
    ]
