# Generated by Django 4.2 on 2023-04-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_weekly_weight_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_weight_change',
        ),
    ]
