# Generated by Django 4.2 on 2023-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_weekly_weight_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
