# Generated by Django 4.2 on 2023-04-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_foodintake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintake',
            old_name='user',
            new_name='user_profile',
        ),
    ]
