# Generated by Django 4.2 on 2023-04-20 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_foodintake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintake',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='foodintake',
            name='serving_size',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
